"""create in_out

Revision ID: 199385a810b2
Revises: 38b376ab0203
Create Date: 2026-01-30 17:59:31.941778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199385a810b2'
down_revision: Union[str, Sequence[str], None] = '38b376ab0203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_out',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('in_time', sa.DateTime()),
    sa.Column('out_time', sa.DateTime()),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'])

    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('in_out')
    # ### end Alembic commands ###



