"""create github_accounts

Revision ID: 38b376ab0203
Revises: b87747f11024
Create Date: 2026-01-30 11:03:13.374366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '38b376ab0203'
down_revision: Union[str, Sequence[str], None] = 'b87747f11024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('github_username', sa.String()),
    sa.Column('access_token', sa.String()),
    sa.Column('created_at', sa.DateTime(),default=datetime.utcnow()),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'])

    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_accounts')
    # ### end Alembic commands ###



