"""initial tables

Revision ID: 90e6e657942b
Revises: af05625b4695
Create Date: 2026-01-02 16:04:29.064067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '90e6e657942b'
down_revision: Union[str, Sequence[str], None] = 'af05625b4695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('activity_events',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('userid', sa.String(), nullable=True),
#     sa.Column('event_type', sa.String(), nullable=True),
#     sa.Column('duration_minutes', sa.Integer(), nullable=True),
#     sa.Column('timestamp', sa.DateTime(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('features',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('userid', sa.String(), nullable=True),
#     sa.Column('focus_score', sa.Float(), nullable=True),
#     sa.Column('fatigue_score', sa.Float(), nullable=True),
#     sa.Column('context_switch_rate', sa.Float(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('feedback',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('userid', sa.String(), nullable=True),
#     sa.Column('suggestion', sa.String(), nullable=True),
#     sa.Column('accepted', sa.Boolean(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('users',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('name', sa.String(), nullable=True),
#     sa.Column('role', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('users')
#     op.drop_table('feedback')
#     op.drop_table('features')
#     op.drop_table('activity_events')
#     # ### end Alembic commands ###





# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('activity_text',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('userid', sa.String(), nullable=False),
#     sa.Column('message', sa.String(), nullable=False),
#     sa.Column('created_at', sa.DateTime(),default=datetime.utcnow()),
#     sa.PrimaryKeyConstraint('id'),
#     sa.ForeignKeyConstraint(['userid'], ['users.id'])

#     )
    
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('activity_text')
#     # ### end Alembic commands ###


