"""add activity_text table

Revision ID: b87747f11024
Revises: 90e6e657942b
Create Date: 2026-01-12 16:07:25.074042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'b87747f11024'
down_revision: Union[str, Sequence[str], None] = '90e6e657942b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_text',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(),default=datetime.utcnow()),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'])

    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_text')
    # ### end Alembic commands ###


